# Generated by Django 5.1.3 on 2024-11-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='telegram_id',
            field=models.CharField(max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
