# Generated by Django 5.1.3 on 2024-11-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextended_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='receive_event_reminders',
            field=models.BooleanField(default=True, verbose_name='Получать напоминания о мероприятиях'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='receive_event_update_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления об изменениях в мероприятиях'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='receive_new_event_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления о новых мероприятиях'),
        ),
    ]
