# Generated by Django 5.1.3 on 2024-11-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='№')),
                ('sm_in_ekp', models.CharField(max_length=255, verbose_name='СМ в ЕКП')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование спортивного мероприятия')),
                ('gender_age_group', models.CharField(max_length=255, verbose_name='Пол, возрастная группа')),
                ('discipline_program', models.CharField(max_length=255, verbose_name='Дисциплина, программа')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Субъект РФ')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('venue', models.CharField(max_length=255, verbose_name='Спортивная база, центр')),
                ('participants', models.PositiveIntegerField(verbose_name='Количество участников (чел.)')),
                ('sport_type', models.CharField(max_length=255, verbose_name='Вид спорта')),
                ('event_type', models.CharField(max_length=255, verbose_name='Тип соревнования')),
            ],
        ),
    ]
