# Generated by Django 5.1.3 on 2024-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_competitiontype_sport_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('canceled', 'Отменено'), ('moved', 'Перенесено')], default='active', max_length=10, verbose_name='Статус мероприятия'),
        ),
    ]
