# Generated by Django 5.1.3 on 2024-11-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILURE', 'Ошибка')], max_length=20, verbose_name='Статус парсинга')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лог парсинга',
                'verbose_name_plural': 'Логи парсинга',
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_uploads/', verbose_name='PDF-файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('parsed', models.BooleanField(default=False, verbose_name='Распарсен')),
                ('parsing_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.parsinglog', verbose_name='Лог парсинга')),
            ],
            options={
                'verbose_name': 'Загрузка PDF',
                'verbose_name_plural': 'Загрузки PDF',
            },
        ),
    ]
