# Generated by Django 5.1.3 on 2024-11-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsinglog',
            name='errors',
            field=models.JSONField(blank=True, help_text='Список ошибок, произошедших при парсинге', null=True, verbose_name='Ошибки'),
        ),
    ]
