version: "3.9"

services:
  core:
    build: ../core
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - "8000:8000" # API доступен на локальной машине
    env_file:
      - ../.env
    depends_on:
      - postgres_db
      - redis
    environment:
      - POSTGRES_HOST=postgres_db
      - REDIS_HOST=redis

  postgres_db:
    image: postgres:16
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume: