# Generated by Django 5.1.3 on 2024-11-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_EVENT', 'Новое мероприятие'), ('EVENT_UPDATE', 'Обновление мероприятия'), ('REMINDER', 'Напоминание')], max_length=124, verbose_name='Тип уведомления'),
        ),
    ]
