# Generated by Django 5.1.3 on 2024-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('receive_new_event_notifications', 'Новое мероприятие'), ('receive_event_update_notifications', 'Обновление мероприятия'), ('receive_event_reminders', 'Напоминание')], max_length=124, verbose_name='Тип уведомления'),
        ),
    ]
